---
title: "Analyse scores"
author: John Reid
output: html_document
params:
  scores.file: ../slurm/scores.tsv
---

```{r renderMe, eval = FALSE, echo = FALSE}
#
# Execute this block to render this document.
#
devtools::load_all()
rmarkdown::render("analyse-scores.Rmd")
```

Load the scores.
```{r loadScores}
library(Saturn)
library(ggplot2)
library(ggthemes)
scores.file <- params$scores.file
# scores.file <- '../slurm/scores.tsv'
scores <- readr::read_tsv(scores.file)
```

Parse the filenames.
```{r parseFilename}
parsed <- as.data.frame(stringr::str_split_fixed(basename(scores$file), '\\.', 5)[,2:4])
colnames(parsed) <- c('TF', 'cell', 'motifs')
parsed <-
    parsed %>%
    mutate(
        TF = factor(TF, tf.levels),
        cell.valid = factor(cell, cell.levels),
        motifs.simple = factor(stringr::str_replace(motifs, 'DREME-.+', 'DREME')))
sapply(parsed, class)
scores <- cbind(scores, parsed)
```

Filter those TFs/cell combos for which we have all the motif tags.
```{r filterHaveAll}
have.all.motif.tags <-
    scores %>%
    group_by(TF, cell.valid) %>%
    summarise(n = n()) %>%
    filter(length(levels(scores$motifs.simple)) == n)
scores.good <- have.all.motif.tags %>% left_join(scores)
```

Simple plots.
```{r simplePlots}
ggplot(scores.good, aes(x = motifs.simple, y = AUPRC)) +
    geom_boxplot() +
    facet_wrap(~ TF) +
    theme_few()
ggplot(scores.good, aes(x = motifs.simple, y = recall_05)) +
    geom_boxplot() +
    facet_wrap(~ TF) +
    theme_few()
ggplot(scores.good, aes(x = motifs.simple, y = recall_10)) +
    geom_boxplot() +
    facet_wrap(~ TF) +
    theme_few()
ggplot(scores.good, aes(x = motifs.simple, y = recall_25)) +
    geom_boxplot() +
    facet_wrap(~ TF) +
    theme_few()
ggplot(scores.good, aes(x = motifs.simple, y = recall_50)) +
    geom_boxplot() +
    facet_wrap(~ TF) +
    theme_few()
```
