#!/usr/bin/env python

from prg import prg
import pandas as pd

df = pd.read_table('dt.valid.tsv')
labels = (df.bound == 'B').values.astype(int)
scores = df.predictions.values
prg_curve = prg.create_prg_curve(labels, scores)
auprg = prg.calc_auprg(prg_curve)
print(auprg)
plt = prg.plot_prg(prg_curve)
plt.savefig('PRG.png')
