#!/bin/bash -e
USAGE="$0 <markdown>"
MD=${1?:$USAGE}
shift
BASE=$(basename "$MD" .md)
OUT="$BASE.pdf"
pandoc \
     --filter pandoc-citeproc \
     -V links-as-notes=true \
     "$@" \
     $MD -o $OUT
